### ISSUE TITLE
更多功能建议

### ISSUE THREAD

**Issue by Jinnrry** [Jacknic/glut#2]
我之前做过一些，既然你先做出来了，我分享给你吧，图书馆是可以在线续借、查询借阅记录、查询欠费、缴费等操作的，地址：http://202.193.80.181:8080/opac/reader/doLogin   我做过PHP-curl爬虫实现

易班上面可以爬取体测数据：地址http://202.193.80.60/glutlife/grade  但是跳转很多，写爬虫比较麻烦

另外，想问问你项目的爬虫是怎么实现的，我找了好久都没找到你爬虫部分的代码，我用httpclient写了上千行的爬虫代码，你的项目中就找到几行OkGo，不知道这是不是爬虫代码？

**Comment by Jinnrry** [comment]
你项目的网络部分实在看不懂啊，比如你反馈功能，我根本找不到提交代码

**Comment by Jacknic** [comment]
你好，是的，网络爬虫和服务器交互都是使用了OkGO，然后通过Jsoup解析html内容。
反馈是使用了腾讯开放平台数据统计的SDK，代码写的比较乱多多担待 :）

**Comment by Jacknic** [comment]
图书馆部分，下一个版本应该可以添加上去，这次只是占个位置。
爬取易班的数据，还得易班账号登陆，有点麻烦

**Comment by chrrg877562884** [comment]
易班技术中心了解一下
